#!/bin/sh

echo "Ten database su dung cho zabbix:"
read DB

echo "Ten user co quyen voi database $DB:"
read user

cd 
mkdir zabbix-backup-file

mysqldump -u $user -p $DB $(cat tables) > zabbix-backup-file/zabbix-`date +"%Y-%m-%d-%H-%M-%S"`.sql

