#!/bin/sh

mkdir zabbix

cd zabbix

wget https://raw.githubusercontent.com/niemdinhtrong/ghichep-zabbix/master/scripts/zabbix-backup

wget https://raw.githubusercontent.com/niemdinhtrong/ghichep-zabbix/master/scripts/tables

sudo chmod +x zabbix-backup

./zabbix-backup

